import { ArrowRight, Check, Compass, Eye, Layers3, Route } from 'lucide-react';
import { Link } from 'wouter';
import { ArrowLink, Callout, SectionHeading, Seo } from '@/components/site';

const principles = [
  { icon: Compass, title: 'Context first', copy: 'The right answer depends on the business, the market, and the moment.' },
  { icon: Eye, title: 'Signal over noise', copy: 'We look for the few choices that make many other choices easier.' },
  { icon: Layers3, title: 'Systems that stick', copy: 'Good work leaves your team with something they can run and improve.' },
  { icon: Route, title: 'Momentum matters', copy: 'A useful next step is better than a perfect plan that never ships.' },
];

export default function About() {
  return <><Seo title="About Numero Minds | Digital growth made simple" description="Get to know Numero Minds: a practical digital growth partner for small and growing businesses in Hyderabad and beyond." path="/about" />
    <section className="container-wide pt-36 sm:pt-48"><p className="eyebrow reveal">About / the point of view</p><h1 className="display reveal reveal-delay-1 mt-6 max-w-5xl text-balance text-6xl font-extrabold leading-[.9] sm:text-8xl">Simple is not<br /><span className="text-gradient">small thinking.</span></h1><div className="mt-10 grid gap-8 border-b border-slate-200 pb-16 md:grid-cols-[1fr_.7fr] md:items-end"><p className="max-w-2xl text-xl font-semibold leading-8 text-slate-800">Numero Minds exists to help growing businesses use digital with more intention — and less noise.</p><p className="text-sm leading-7 text-slate-600">We are a digital growth partner based in Hyderabad, working across the connected work of positioning, experience, acquisition, and operations.</p></div></section>
    <section className="container-wide py-24 sm:py-32"><div className="grid gap-12 lg:grid-cols-[.8fr_1.2fr]"><SectionHeading eyebrow="The work behind the work" title="A capable partner for the bit that comes after the idea." /><div className="space-y-7 text-base leading-8 text-slate-600"><p>Growing a business is full of decisions that seem separate until they start to compound. What do you say? Where do people find you? How do you follow up? Which tool will the team actually use?</p><p>We bring those questions into one room. Our work sits at the intersection of clear communication, thoughtful digital experiences, and practical operating systems.</p><p className="font-semibold text-slate-900">The result is not digital for its own sake. It is a business that is easier to understand, easier to choose, and easier to run.</p></div></div></section>
    <section className="border-y border-slate-200 bg-blue-50/55 py-24 sm:py-32"><div className="container-wide"><SectionHeading eyebrow="Our philosophy" title="Make the complicated legible." copy="Affordable professional digital solutions should feel clear from the first conversation to the final handover." /><div className="mt-14 grid gap-0 overflow-hidden rounded-3xl border border-slate-200 bg-white sm:grid-cols-2 lg:grid-cols-4">{principles.map(({ icon: Icon, title, copy }, index) => <div key={title} className="border-b border-slate-200 p-6 last:border-b-0 sm:border-r lg:border-b-0 lg:last:border-r-0"><Icon className={`h-6 w-6 ${index % 2 ? 'text-secondary' : 'text-primary'}`} /><h3 className="mt-12 font-display text-xl font-extrabold">{title}</h3><p className="mt-3 text-sm leading-6 text-slate-600">{copy}</p></div>)}</div></div></section>
    <section className="container-wide py-24 sm:py-32"><div className="grid gap-14 lg:grid-cols-[1fr_.8fr]"><div><SectionHeading eyebrow="Why businesses choose us" title="Clarity is a competitive advantage." /><div className="mt-10 space-y-5">{['Senior thinking without the performance', 'A connected view of marketing and operations', 'Recommendations that respect your team and budget', 'A partner who can explain the why'].map((item) => <div key={item} className="flex items-center gap-4 border-b border-slate-200 pb-5 text-sm font-semibold text-slate-800"><span className="flex h-6 w-6 items-center justify-center rounded-md border border-emerald-200 bg-emerald-50 text-emerald-600"><Check className="h-3.5 w-3.5" /></span>{item}</div>)}</div></div><div className="grid-surface flex min-h-[360px] items-end rounded-3xl border border-slate-200 bg-white p-7 shadow-sm"><div><p className="font-mono text-5xl font-bold text-primary">NM<span className="text-accent">/</span>01</p><p className="mt-5 max-w-xs text-sm leading-6 text-slate-600">A small, focused partner for businesses building their next stage.</p></div></div></div></section>
    <section className="container-wide pb-24 sm:pb-32"><div className="rounded-3xl border-l-4 border-primary bg-white p-6 shadow-sm sm:p-10"><p className="eyebrow">How we work</p><p className="display mt-5 max-w-4xl text-4xl font-extrabold leading-tight sm:text-6xl">Listen carefully. Shape clearly. Move usefully.</p><p className="mt-7 max-w-2xl text-sm leading-7 text-slate-600">We start with the business context, make a focused plan your team can understand, then ship and learn with more signal.</p><Link href="/services" className="mt-7 inline-flex items-center gap-2 text-sm font-bold text-primary" data-testid="link-about-services">Explore our services <ArrowRight className="h-4 w-4" /></Link></div></section><Callout title="Bring us the messy version." copy="We are good at finding the useful thread. Start with a conversation, not a perfect brief." />
  </>;
}