import { ArrowDown, ArrowRight, Check, CircleCheck, LayoutDashboard, Sparkles, Workflow } from 'lucide-react';
import { Link } from 'wouter';
import { ArrowLink, Callout, FaqAccordion, SectionHeading, Seo, ServiceIcon } from '@/components/site';
import { services } from '@/lib/site-config';

function GrowthDashboard() {
  return (
    <div className="relative mx-auto w-full max-w-[510px] reveal reveal-delay-2">
      <div className="absolute -inset-8 rounded-[3rem] bg-blue-100/70 blur-3xl" />
      <div className="relative rounded-3xl border border-slate-200 bg-white p-4 shadow-2xl shadow-blue-900/10 sm:p-6">
        <div className="flex items-center justify-between border-b border-slate-100 pb-4">
          <div className="flex items-center gap-2"><span className="flex h-8 w-8 items-center justify-center rounded-lg bg-blue-50 text-primary"><LayoutDashboard className="h-4 w-4" /></span><div><p className="text-xs font-extrabold text-slate-900">Growth overview</p><p className="text-[10px] text-slate-400">Conceptual dashboard</p></div></div>
          <span className="rounded-full bg-emerald-50 px-2.5 py-1 font-mono text-[9px] font-bold text-emerald-700">ON TRACK</span>
        </div>
        <div className="mt-5 grid grid-cols-[1fr_116px] gap-4">
          <div className="rounded-2xl bg-slate-50 p-3">
            <div className="flex items-center justify-between"><span className="font-mono text-[9px] font-bold tracking-wider text-slate-400">GROWTH SIGNAL</span><span className="text-[10px] font-bold text-emerald-600">+ clarity</span></div>
            <svg viewBox="0 0 350 158" className="mt-4 h-40 w-full" role="img" aria-label="Conceptual upward growth chart">
              <defs><linearGradient id="areaFill" x1="0" x2="0" y1="0" y2="1"><stop offset="0" stopColor="hsl(224 76% 48% / .2)" /><stop offset="1" stopColor="hsl(224 76% 48% / 0)" /></linearGradient></defs>
              {[30, 70, 110, 150].map((y) => <line key={y} x1="0" x2="350" y1={y} y2={y} stroke="hsl(214 30% 88% / .75)" strokeWidth="1" />)}
              <path d="M0 136 C36 130 45 116 76 120 S112 91 145 101 S180 76 212 83 S250 58 278 67 S319 26 350 25 V158 H0Z" fill="url(#areaFill)" />
              <path className="line-draw" d="M0 136 C36 130 45 116 76 120 S112 91 145 101 S180 76 212 83 S250 58 278 67 S319 26 350 25" fill="none" stroke="hsl(224 76% 48%)" strokeLinecap="round" strokeWidth="3" />
              <circle cx="350" cy="25" r="5" fill="hsl(188 82% 39%)" />
            </svg>
            <div className="mt-1 flex justify-between font-mono text-[9px] text-slate-400"><span>NOW</span><span>NEXT</span><span>READY</span></div>
          </div>
          <div className="space-y-3">
            <div className="rounded-2xl border border-slate-100 bg-white p-3 shadow-sm"><p className="font-mono text-[8px] font-bold tracking-wider text-slate-400">FOCUS</p><p className="mt-2 text-xs font-bold text-slate-800">Positioning</p><div className="mt-3 h-1.5 overflow-hidden rounded-full bg-blue-50"><div className="h-full w-4/5 rounded-full bg-primary" /></div></div>
            <div className="rounded-2xl border border-slate-100 bg-white p-3 shadow-sm"><p className="font-mono text-[8px] font-bold tracking-wider text-slate-400">NEXT SIGNAL</p><p className="mt-2 text-xs font-bold text-slate-800">Better enquiries</p><CircleCheck className="mt-3 h-4 w-4 text-emerald-500" /></div>
          </div>
        </div>
        <div className="mt-4 grid grid-cols-3 divide-x divide-slate-100 rounded-2xl bg-slate-50 py-3 text-center"><div><p className="font-mono text-[8px] text-slate-400">MESSAGE</p><p className="mt-1 text-xs font-bold text-slate-800">Clear</p></div><div><p className="font-mono text-[8px] text-slate-400">SYSTEM</p><p className="mt-1 text-xs font-bold text-slate-800">Useful</p></div><div><p className="font-mono text-[8px] text-slate-400">MOTION</p><p className="mt-1 text-xs font-bold text-emerald-600">Ready</p></div></div>
      </div>
      <div className="float absolute -bottom-7 -left-5 hidden items-center gap-3 rounded-2xl border border-slate-200 bg-white p-3 shadow-xl shadow-blue-900/10 sm:flex"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-cyan-50 text-accent"><Workflow className="h-4 w-4" /></span><div><p className="text-[10px] font-bold text-slate-900">Connected thinking</p><p className="text-[10px] text-slate-400">Build. Market. Automate.</p></div></div>
    </div>
  );
}

export default function Home() {
  return <><Seo title="Numero Minds | Digital Growth Made Simple." description="Numero Minds helps growing businesses build, market, automate, and grow with affordable professional digital solutions." path="/" faq />
    <section className="container-wide grid min-h-[760px] items-center gap-16 pb-20 pt-36 lg:grid-cols-[1fr_.92fr] lg:gap-20">
      <div className="reveal"><div className="mb-7 flex items-center gap-3"><span className="eyebrow">Digital growth partner / Hyderabad + beyond</span><span className="h-px w-12 bg-primary/40" /></div><h1 className="display max-w-3xl text-balance text-[clamp(3.25rem,7vw,6.8rem)] font-extrabold leading-[.91] text-slate-950">Digital growth<br /><span className="text-gradient">made simple.</span></h1><p className="mt-8 max-w-xl text-lg leading-8 text-slate-600">Affordable professional digital solutions for growing businesses. We bring your website, marketing, automation, and operations into a clearer path forward.</p><div className="mt-9 flex flex-wrap items-center gap-5"><ArrowLink href="/contact">Get Started</ArrowLink><Link href="/services" className="group inline-flex items-center gap-2 text-sm font-bold text-slate-600 transition hover:text-primary" data-testid="link-hero-services">Explore services <ArrowRight className="h-4 w-4 transition-transform group-hover:translate-x-1" /></Link></div><div className="mt-14 flex flex-wrap items-center gap-4 text-xs font-semibold text-slate-500"><span className="flex h-8 w-8 items-center justify-center rounded-lg border border-emerald-200 bg-emerald-50 text-emerald-600"><Check className="h-4 w-4" /></span><span>Clear plans</span><span className="h-1 w-1 rounded-full bg-slate-300" /><span>Practical systems</span><span className="h-1 w-1 rounded-full bg-slate-300" /><span>Useful momentum</span></div></div>
      <GrowthDashboard />
    </section>
    <section className="border-y border-slate-200 bg-white py-7"><div className="container-wide flex flex-wrap items-center justify-between gap-5"><p className="font-mono text-[10px] font-bold tracking-[.16em] text-slate-400">BUILT FOR THE NEXT STAGE OF BUSINESS</p><div className="flex flex-wrap gap-x-7 gap-y-2 text-sm font-semibold text-slate-500"><span>Founders</span><span>Marketing teams</span><span>Operators</span><span>Growing businesses</span></div></div></section>
    <section className="container-wide py-24 sm:py-32"><div className="grid gap-14 lg:grid-cols-[.8fr_1.2fr]"><SectionHeading eyebrow="A connected approach" title="Every digital decision should make the next one easier." copy="Your website, campaigns, store, and internal systems do not have to live in separate worlds. We connect the right pieces around the business you are building." /><div className="grid gap-4 sm:grid-cols-2"><div className="rounded-2xl border border-blue-100 bg-blue-50/60 p-6"><span className="font-mono text-3xl font-bold text-primary">01</span><h3 className="mt-12 font-display text-xl font-extrabold">Find the signal</h3><p className="mt-3 text-sm leading-6 text-slate-600">Make the offer, audience, and immediate constraint easier to see.</p></div><div className="mt-8 rounded-2xl border border-violet-100 bg-violet-50/50 p-6 sm:mt-16"><span className="font-mono text-3xl font-bold text-secondary">02</span><h3 className="mt-12 font-display text-xl font-extrabold">Build the system</h3><p className="mt-3 text-sm leading-6 text-slate-600">Turn the right idea into a useful digital experience your team can run.</p></div></div></div></section>
    <section className="container-wide pb-24 sm:pb-32"><div className="flex flex-col justify-between gap-7 border-b border-slate-200 pb-8 sm:flex-row sm:items-end"><SectionHeading eyebrow="What we do" title="Build. Market. Automate. Grow." /><Link href="/services" className="group inline-flex items-center gap-2 pb-1 text-sm font-bold text-primary" data-testid="link-home-all-services">View all services <ArrowRight className="h-4 w-4 transition-transform group-hover:translate-x-1" /></Link></div><div className="grid md:grid-cols-2 lg:grid-cols-3">{services.map((service, index) => <Link key={service.id} href={`/services#${service.id}`} className={`group min-h-[260px] border-b border-slate-200 p-6 transition hover:-translate-y-1 hover:bg-white hover:shadow-lg hover:shadow-slate-200/70 ${index % 3 !== 2 ? 'lg:border-r' : ''} ${index % 2 === 0 ? 'md:border-r lg:border-r' : ''}`} data-testid={`card-home-service-${service.id}`}><div className="flex items-start justify-between"><ServiceIcon type={service.icon} /><span className="font-mono text-xs font-bold text-slate-400">{service.number}</span></div><h3 className="mt-14 font-display text-2xl font-extrabold">{service.title}</h3><p className="mt-3 text-sm leading-6 text-slate-600">{service.short}</p><ArrowRight className="mt-6 h-4 w-4 text-primary opacity-0 transition group-hover:translate-x-1 group-hover:opacity-100" /></Link>)}</div></section>
    <section className="container-wide pb-24 sm:pb-32"><div className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm sm:p-10"><div className="grid gap-10 lg:grid-cols-[.8fr_1.2fr]"><div><p className="eyebrow mb-5">Attract to grow</p><h2 className="display max-w-xl text-4xl font-extrabold leading-[.98] sm:text-5xl">A journey your customer can actually follow.</h2><p className="mt-5 max-w-md text-sm leading-7 text-slate-600">We help you move from being discovered to being chosen, then keep the relationship useful after the first conversion.</p></div><div className="grid gap-3 sm:grid-cols-4">{['Attract', 'Engage', 'Convert', 'Grow'].map((step, index) => <div key={step} className="relative rounded-2xl bg-slate-50 p-5"><span className="font-mono text-[10px] font-bold text-primary">0{index + 1}</span><h3 className="mt-12 font-display text-lg font-extrabold">{step}</h3><ArrowDown className="mt-6 h-4 w-4 text-slate-300 sm:hidden" />{index < 3 && <ArrowRight className="absolute -right-3 top-1/2 z-10 hidden h-5 w-5 -translate-y-1/2 text-primary sm:block" />}</div>)}</div></div></div></section>
    <section className="container-wide pb-24 sm:pb-32"><div className="grid gap-10 rounded-3xl bg-slate-950 px-6 py-10 text-white sm:px-12 sm:py-14 lg:grid-cols-[.8fr_1.2fr]"><div><p className="mb-5 font-mono text-[10px] font-bold tracking-[.17em] text-cyan-300">WHY NUMERO MINDS</p><h2 className="display text-4xl font-extrabold leading-[.98] sm:text-5xl">Clear enough to use. Ambitious enough to matter.</h2></div><div className="grid gap-8 sm:grid-cols-3"><div><Sparkles className="h-5 w-5 text-cyan-300" /><p className="mt-5 text-sm leading-6 text-slate-300">Senior thinking without agency theatre.</p></div><div><Workflow className="h-5 w-5 text-violet-300" /><p className="mt-5 text-sm leading-6 text-slate-300">Connected marketing and operations.</p></div><div><Check className="h-5 w-5 text-emerald-300" /><p className="mt-5 text-sm leading-6 text-slate-300">Recommendations that respect your team and budget.</p></div></div></div></section>
    <section className="container-wide pb-24 sm:pb-32"><SectionHeading eyebrow="Demo work" title="A glimpse of what useful can look like." copy="Sample directions, clearly labeled. A view into how we think, not a list of invented client results." /><div className="mt-10 grid gap-4 md:grid-cols-[1.2fr_.8fr]"><div className="relative min-h-[360px] overflow-hidden rounded-3xl border border-slate-200 bg-blue-50 p-7"><div className="absolute right-8 top-8 h-48 w-48 rounded-full border-[22px] border-white/70 bg-cyan-200/50" /><div className="relative flex h-full flex-col justify-between"><span className="eyebrow">Demo / Sample — Website</span><div><h3 className="display max-w-sm text-4xl font-extrabold">Atlas Workshop<span className="text-primary">.</span></h3><p className="mt-3 max-w-sm text-sm leading-6 text-slate-600">A clearer digital front door for a specialist fabrication studio.</p></div></div></div><div className="flex min-h-[360px] flex-col justify-between rounded-3xl border border-slate-200 bg-violet-50/60 p-7"><Sparkles className="h-6 w-6 text-secondary" /><div><span className="eyebrow text-secondary">Demo / Sample — Systems</span><h3 className="display mt-5 text-3xl font-extrabold">Orbit Commerce</h3><p className="mt-3 text-sm leading-6 text-slate-600">A lean lead-to-order view for a growing distribution team.</p><Link href="/portfolio" className="mt-8 inline-flex items-center gap-2 text-sm font-bold text-primary" data-testid="link-home-portfolio">View the portfolio <ArrowRight className="h-4 w-4" /></Link></div></div></div></section>
    <section className="container-wide grid gap-12 pb-24 sm:pb-32 lg:grid-cols-[.8fr_1.2fr]"><SectionHeading eyebrow="Questions, answered" title="A few useful starting points." copy="Still deciding where to begin? These may help." /><FaqAccordion /></section>
    <Callout title="Your next useful move starts here." copy="Tell us where growth feels stuck. We will help you see the path forward." />
  </>;
}