import { ArrowRight, Check, MousePointer2 } from 'lucide-react';
import { Link } from 'wouter';
import { Callout, SectionHeading, Seo, ServiceIcon } from '@/components/site';
import { services } from '@/lib/site-config';

export default function Services() {
  return <><Seo title="Services | Numero Minds digital growth" description="Explore website development, social media, performance marketing, e-commerce, and ERP/CRM support from Numero Minds." path="/services" />
    <section className="container-wide pt-36 sm:pt-48"><p className="eyebrow reveal">Services / the connected view</p><h1 className="display reveal reveal-delay-1 mt-6 max-w-4xl text-balance text-6xl font-extrabold leading-[.9] sm:text-8xl">Build the parts.<br /><span className="text-gradient">Connect the whole.</span></h1><p className="mt-9 max-w-2xl text-lg leading-8 text-slate-600">Choose the work that matters now. We will keep an eye on what it needs to connect to later.</p></section>
    <section className="container-wide py-24 sm:py-32">{services.map((service, index) => <article id={service.id} key={service.id} className="scroll-mt-24 border-t border-slate-200 py-14 sm:py-20"><div className={`grid gap-8 lg:grid-cols-[.18fr_1fr_.72fr] ${index % 2 ? 'lg:bg-blue-50/40' : ''}`}><div className="flex items-start justify-between lg:block"><span className="font-mono text-3xl font-bold text-primary">{service.number}</span><div className="mt-4 hidden lg:block"><ServiceIcon type={service.icon} /></div></div><div><p className="eyebrow">{service.title}</p><h2 className="display mt-5 max-w-xl text-4xl font-extrabold leading-[.98] sm:text-5xl">{service.short}</h2><p className="mt-7 max-w-xl text-base leading-7 text-slate-600">{service.body}</p><Link href="/contact" className="group mt-8 inline-flex items-center gap-2 rounded-lg bg-primary px-4 py-3 text-sm font-bold text-white shadow-sm shadow-primary/20 transition hover:-translate-y-0.5 hover:bg-secondary" data-testid={`link-service-enquiry-${service.id}`}>Enquire about {service.title} <ArrowRight className="h-4 w-4 transition-transform group-hover:translate-x-1" /></Link></div><div className="self-end rounded-2xl border border-slate-200 bg-white p-6 shadow-sm lg:ml-4"><p className="font-mono text-[10px] font-bold tracking-[.15em] text-slate-400">WHAT THIS CAN UNLOCK</p><ul className="mt-6 space-y-4">{service.outcomes.map((outcome) => <li key={outcome} className="flex items-center gap-3 text-sm font-semibold text-slate-700"><Check className="h-4 w-4 text-accent" />{outcome}</li>)}</ul><MousePointer2 className="mt-7 h-5 w-5 text-blue-200" /></div></div></article>)}</section>
    <section className="container-wide pb-24 sm:pb-32"><SectionHeading eyebrow="Not sure where to start?" title="Start with the constraint you can feel." copy="We will help you turn it into a clear first move — whether that leads to a website, a campaign, or a better system." /><Link href="/contact" className="mt-8 inline-flex items-center gap-2 rounded-lg bg-primary px-5 py-3 text-sm font-bold text-white shadow-sm shadow-primary/20 hover:bg-secondary" data-testid="link-services-cta">Talk through your next move <ArrowRight className="h-4 w-4" /></Link></section><Callout />
  </>;
}